Clean

diff --git a/src/build b/src/build
--- a/src/build
+++ b/src/build
@@ -1,55 +1,56 @@
 #!/usr/bin/env bash
 
-Program="${0##*/}"
-SRCDIR="${SRCDIR:-$HOME/.local/src}"
-
-[[ -d "$SRCDIR" ]] || mkdir -p -- "$SRCDIR"
-
-Usage() {
-	read -d '' <<-EOF
-		Usage: $Program [OPTION/AUR]
-		To remove the AUR, use \`pacman -Rns \$AUR\`.
-
-		  -h, --help        - Display this help infomation.
-		  -c, --check       - Check AUR's in \$SRCDIR, if up to date or not.
-
-	EOF
-
-	printf '%s' "$REPLY"
-}
+progrm=${0##*/}
+src_dir=$HOME/.local/src
 
 Err() {
-	printf '%s\n' "$Program: $2" 1>&2
+	printf '%s\n' "$progrm: $2" 1>&2
 	(( $1 > 0 )) && exit $1
 }
 
-((UID)) || Err 2 'denied to run as root...'
+((UID)) || Err 1 'denied to run as root...'
 
-for Dep in git makepkg; {
-	if ! type -P "$Dep" &>/dev/null; then
+for dep in git makepkg; {
+	if ! type -P "$dep" &>/dev/null; then
 		Err 0 "dependency, \`$Dep\`, not met..."
-		(( DepErr++ ))
+		(( dep_err++ ))
 	fi
 }
 
-(( DepErr )) && Err 1 "$DepErr dependency(s) missing, aborted..."
-unset -v DepErr
+(( dep_err )) && Err 1 "$dep_err dependency(s) missing, aborted..."
+unset -v dep_err
+
+[[ -d $src_dir ]] || mkdir -p -- "$src_dir"
 
 if [[ -z $1 ]]; then
 	Err 0 'no argument were given...'
-	printf '%s\n' "See \`$Program --help\` for usage." 1>&2
-	exit 2
+	printf '%s\n' "See \`$progrm --help\` for usage." 1>&2
+	exit 1
 fi
 
 while [[ -n $1 ]]; do
 	case $1 in
 		-h|--help)
-			Usage
+			read -d '' <<-EOF
+				Usage: $progrm [OPTION/AUR]
+				To remove the AUR, use \`pacman -Rns \$AUR\`.
+
+				  -h, --help        - Display this help infomation.
+				  -C, --check       - Check AUR's if up to date or not.
+
+			EOF
+
+			printf '%s' "$REPLY"
 			exit 0 ;;
 
-		-c|--check)
-			for AUR in "$SRCDIR"/*/PKGBUILD; {
-				git -C "${AUR%/*}" pull -q
+		-C|--check)
+			for aur in "$src_dir"/*/PKGBUILD; {
+				aur=${aur%/*}
+
+				printf '%s' "${aur##*/}: "
+				git -C "$aur" pull
+
+				printf '\n'
 			}
 
 			exit 0 ;;
@@ -59,7 +60,7 @@ while [[ -n $1 ]]; do
 			break ;;
 
 		-*)
-			Err 2 "$1: invaild option..." ;;
+			Err 1 "$1: invaild option..." ;;
 
 		*)
 			break ;;
@@ -67,28 +68,28 @@ while [[ -n $1 ]]; do
 	shift
 done
 
-(( $# > 1 )) && Err 2 "can't build multiple AUR's at a time..."
+(( $# > 1 )) && Err 1 "can't build multiple AUR's at a time..."
 
 if [[ -d $1 ]]; then
-	AUR="$1"
+	aur=$1
 else
-	URL=https://aur.archlinux.org/"$1"
-	AUR="$SRCDIR/$1"
+	url=https://aur.archlinux.org/$1
+	aur=$src_dir/$1
 
-	if [[ -d $AUR ]]; then
-		git -C "$AUR" pull -q
+	if [[ -d $aur ]]; then
+		git -C "$aur" pull -q
 	else
-		Err 0 "'$1' not found use \`git clone\` instead..."
-		git clone -q "$URL" "$AUR" || Err 1 'failed to use `git clone`...'
+		Err 0 "'$1' not found, use \`git clone\` instead..."
+		git clone -q "$url" "$aur" || Err 1 'failed to use `git clone`...'
 	fi
 
-	unset -v URL
+	unset -v url
 fi
 
-BuildDIR="${TMPDIR:-/tmp}/build-$(( $SRANDOM * $$ ))"
+temp_dir=${TMPDIR:-/tmp}/build-$SRANDOM
 
-cp -r -- "$AUR" "$BuildDIR" || Err 1 'failed to copy the AUR to temporary directory...'
+cp -r -- "$aur" "$temp_dir" || Err 1 'failed to copy the AUR to temp directory...'
 
-trap "rm -rf -- $BuildDIR; sync" EXIT
+trap "rm -rf -- $temp_dir; sync" EXIT
 
-(cd -- "$BuildDIR" && makepkg -sir) || Err 1 "failed to build '$1'..."
+(cd -- "$temp_dir" && makepkg -sir) || Err 1 "failed to build '$1'..."
diff --git a/src/ghpb b/src/ghpb
--- a/src/ghpb
+++ b/src/ghpb
@@ -2,25 +2,25 @@
 
 trap 'sync' EXIT
 
-Program="${0##*/}"
+progrm=${0##*/}
 
 Err() {
-	printf '%s\n' "$Program: $2" 1>&2
+	printf '%s\n' "$progrm: $2" 1>&2
 	(( $1 > 0 )) && exit $1
 }
 
-(( $# > 0 )) && Err 2 "$Program(1) needn't argument..."
+(( $# > 0 )) && Err 1 "$progrm(1) needn't argument..."
 
 if ! type -P git &>/dev/null; then
-	Err 2 'dependency, `git`, not met...'
+	Err 1 'dependency, `git`, not met...'
 fi
 
-GitDIR="$HOME"/GitHub/ides3rt
-BackDIR=/media/"$USER"/USB1p2/GitHub/ides3rt
+git_dir=$HOME/GitHub/ides3rt
+bak_dir=/media/$USER/USB1p2/GitHub/ides3rt
 
-[[ -d $BackDIR ]] || Err 2 "$BackDIR: not a directory..."
+[[ -d $bak_dir ]] || Err 1 "$bak_dir: not a directory..."
 
-Repositories=(
+repo_arr=(
 	Code
 	doasedit
 	dotfiles
@@ -33,33 +33,33 @@ Repositories=(
 	exit
 )
 
-Count=${#Repositories[@]}
+repo_nr=${#repo_arr[@]}
 
-PS3="Select your repository [1-$Count]: "
+PS3="Select your repository [1-$repo_nr]: "
 
-select Repository in "${Repositories[@]}"; do
-	[[ -z $Repository ]] && continue
-	case $Repository in
+select repo in "${repo_arr[@]}"; do
+	[[ -z $repo ]] && continue
+	case $repo in
 		exit)
 			exit 0 ;;
 
 		gists)
-			cp -r -- "$GitDIR"/gists/* "$BackDIR"/gists/ ;;
+			cp -r -- "$git_dir"/gists/* "$bak_dir"/gists/ ;;
 
 		*)
-			DestDIR="$BackDIR/projects/$Repository"
-			[[ -d $DestDIR ]] && rm -rf "$DestDIR"
+			dest_dir=$bak_dir/projects/$repo
+			[[ -d $dest_dir ]] && rm -rf -- "$dest_dir"
 
-			URL=https://github.com/ides3rt/"$Repository"
-			Repodir="$GitDIR/projects/$Repository"
+			url=https://github.com/ides3rt/$repo
+			repo_dir=$git_dir/projects/$repo
 
-			if [[ -d $Repodir ]]; then
-				cp -r -- "$Repodir" "$DestDIR"
+			if [[ -d $repo_dir ]]; then
+				cp -r -- "$repo_dir" "$dest_dir"
 			else
-				Err 0 "$Repodir: not found, use \`git clone\` instead..."
+				Err 0 "$repo_dir: not found, use \`git clone\` instead..."
 
-				if git clone -q "$URL" "$DestDIR"; then
-					Err 0 "$Repository: not found..."
+				if git clone -q "$url" "$dest_dir"; then
+					Err 0 "$repo: not found..."
 				fi
 			fi ;;
 	esac
